### PR TITLE
add -b option for user/password feature

### PR DESCRIPTION
**Pull request by kerphi**
because " -b  Use the password from the command line rather than prompting for it."

### CODE REVIEW

**Comment by ionelmc** [comment]
Hmmmm ... how did it work without that option?

**Comment by kerphi** [comment]
Don't know why ... Maybe it never worked?

**Comment by ionelmc** [comment]
Ooof. You're right.

**Comment by ionelmc** [comment]
Image should be built now. Thanks for the fix.

**Comment by kerphi** [comment]
Great.
Keep up the good work!

**Pull request merged**
